services:
  - type: web
    name: comex-backend
    env: python
    buildCommand: pip install -r requirements-render-minimal.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: COMEX_STAT_API_URL
        sync: false
      - key: COMEX_STAT_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false

